kind: Service
apiVersion: v1
metadata:
  name: sftp
  labels:
    environment: production
spec:
  type: NodePort
  ports:
  - name: ssh
    port: 22
    targetPort: 22
    nodePort: 30022
  selector:
    app: sftp
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sftp-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sftp
    spec:
      volumes:
        - name: users
          secret:
            secretName: users
        - name: gcs-mounts
          configMap:
            name: gcs-mounts
            defaultMode: 0744
      containers:
      - name: sftp
        image: gcr.io/narvar-qa-202121/sftp-gcs:0.1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 22
        volumeMounts:
          - mountPath: /etc/sftp
            name: users
          - mountPath: /etc/sftp.d/
            name: gcs-mounts
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
